extends SceneTree

func _init() -> void:
	call_deferred("_run")

func _run() -> void:
	var packed: PackedScene = load("res://Main.tscn")
	var main = packed.instance()
	get_root().add_child(main)
	yield(self, "idle_frame")
	yield(self, "idle_frame")
	assert(main.model.beat == 0)
	assert(main.get_node("Layout/TopBar/Brand/Title").text == "MAX TABLET")
	assert(main.get_node("Layout/TopBar/Brand/Subtitle").text == "RESILIENT TACTICAL PICTURE // EXERCISE ORION")
	main._next()
	assert(main.model.beat == 1)
	main._toggle_language()
	assert(main.model.profile == "fr")
	assert(main.get_node("Layout/TopBar/Brand/Title").text == "MAX TABLET")
	assert(main.get_node("Layout/TopBar/Brand/Subtitle").text == "SITUATION TACTIQUE RÉSILIENTE // EXERCICE ORION")
	assert(main.map.profile == "fr")
	main._apply_responsive_layout(Vector2(1200, 1920))
	assert(main.layout_mode == "portrait")
	assert(main.content.columns == 1)
	assert(main.team_list.visible)
	assert(not main.get_node("Layout/TopBar/Clock").visible)
	main._apply_responsive_layout(Vector2(600, 1200))
	assert(main.layout_mode == "portrait_compact")
	assert(not main.team_list.visible)
	assert(not main.get_node("Layout/TopBar/BearerSummary").visible)
	assert(main.responsive_scale >= 3.0)
	assert(main.next_button.rect_min_size.x / main.responsive_scale <= 200)
	main._apply_responsive_layout(Vector2(1920, 1200))
	assert(main.layout_mode == "landscape")
	assert(main.content.columns == 2)
	assert(main.team_list.visible)
	var touch := InputEventScreenTouch.new()
	touch.position = main.map._person_screen("raven_1")
	touch.pressed = true
	main.map._gui_input(touch)
	assert(main.model.selected_id == "raven_1")
	print("RESILIENT_TACTICAL_UI_SMOKE_OK")
	quit()
